### PR TITLE
Artisan publish-permission changes

### PR DESCRIPTION
**Pull request by Houbsi**
It now does only the thing automatically what the command says.

For migration you need to add `--migration` and `--seed`.

### CODE REVIEW

**Comment by eramitgupta** [comment]
Hi mate 👋 @Houbsi 
Can you fix conflicts?

**Comment by eramitgupta** [comment]
> Hi mate 👋 @Houbsi Can you fix conflicts?

I just fixed it

**Comment by Houbsi** [comment]
Ahh it's because i based both branches not on each other. Sorry.

**Comment by eramitgupta** [comment]
Hello @Houbsi,

After committing, please run the following command to check for code style issues:

```bash
./vendor/bin/pint --dirty
```

Thanks!

**Comment by Houbsi** [comment]
Pint is not in the package composer.json dev part. Or do you have it integrated into a laravel application and there is pint installed?

**Comment by eramitgupta** [comment]
> Pint is not in the package composer.json dev part. Or do you have it integrated into a laravel application and there is pint installed?

Laravel `Pint` is the default, you can use it

**Comment by Houbsi** [comment]
Ah  okay, i coded in the raw package.. not in a laravel installation. Found the issue

**Comment by eramitgupta** [comment]
> Ah okay, i coded in the raw package.. not in a laravel installation. Found the issue

Are you fixing style issues?
Or should I?

**Comment by Houbsi** [comment]
Could you please? Having trouble with the setup atm.

**Review by eramitgupta — APPROVED** [review]

**Pull request merged**
